# @generated by generate_proto_mypy_stubs.py.  Do not edit!
import sys
from google.protobuf.descriptor import (
    Descriptor as google___protobuf___descriptor___Descriptor,
    FileDescriptor as google___protobuf___descriptor___FileDescriptor,
)

from google.protobuf.internal.containers import (
    RepeatedCompositeFieldContainer as google___protobuf___internal___containers___RepeatedCompositeFieldContainer,
    RepeatedScalarFieldContainer as google___protobuf___internal___containers___RepeatedScalarFieldContainer,
)

from google.protobuf.message import (
    Message as google___protobuf___message___Message,
)

from typing import (
    Iterable as typing___Iterable,
    Mapping as typing___Mapping,
    MutableMapping as typing___MutableMapping,
    Optional as typing___Optional,
    Text as typing___Text,
)

from typing_extensions import (
    Literal as typing_extensions___Literal,
)

builtin___bool = bool
builtin___bytes = bytes
builtin___float = float
builtin___int = int

DESCRIPTOR: google___protobuf___descriptor___FileDescriptor = ...

class OaasServiceDefinition(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    class TagsEntry(google___protobuf___message___Message):
        DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
        key: typing___Text = ...
        value: typing___Text = ...
        def __init__(
            self,
            *,
            key: typing___Optional[typing___Text] = None,
            value: typing___Optional[typing___Text] = None,
        ) -> None: ...
        def ClearField(
            self,
            field_name: typing_extensions___Literal["key", b"key", "value", b"value"],
        ) -> None: ...
    type___TagsEntry = TagsEntry

    namespace: typing___Text = ...
    name: typing___Text = ...
    version: typing___Text = ...
    locations: google___protobuf___internal___containers___RepeatedScalarFieldContainer[
        typing___Text
    ] = ...
    id: typing___Text = ...
    @property
    def tags(self) -> typing___MutableMapping[typing___Text, typing___Text]: ...
    def __init__(
        self,
        *,
        namespace: typing___Optional[typing___Text] = None,
        name: typing___Optional[typing___Text] = None,
        version: typing___Optional[typing___Text] = None,
        tags: typing___Optional[typing___Mapping[typing___Text, typing___Text]] = None,
        locations: typing___Optional[typing___Iterable[typing___Text]] = None,
        id: typing___Optional[typing___Text] = None,
    ) -> None: ...
    def ClearField(
        self,
        field_name: typing_extensions___Literal[
            "id",
            b"id",
            "locations",
            b"locations",
            "name",
            b"name",
            "namespace",
            b"namespace",
            "tags",
            b"tags",
            "version",
            b"version",
        ],
    ) -> None: ...

type___OaasServiceDefinition = OaasServiceDefinition

class OaasServiceId(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    id: typing___Text = ...
    def __init__(
        self,
        *,
        id: typing___Optional[typing___Text] = None,
    ) -> None: ...
    def ClearField(
        self, field_name: typing_extensions___Literal["id", b"id"]
    ) -> None: ...

type___OaasServiceId = OaasServiceId

class OaasResolveServiceResponse(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    @property
    def services(
        self,
    ) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[
        type___OaasServiceDefinition
    ]: ...
    def __init__(
        self,
        *,
        services: typing___Optional[
            typing___Iterable[type___OaasServiceDefinition]
        ] = None,
    ) -> None: ...
    def ClearField(
        self, field_name: typing_extensions___Literal["services", b"services"]
    ) -> None: ...

type___OaasResolveServiceResponse = OaasResolveServiceResponse

class OaasUnregisterServiceResponse(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    result: builtin___bool = ...
    def __init__(
        self,
        *,
        result: typing___Optional[builtin___bool] = None,
    ) -> None: ...
    def ClearField(
        self, field_name: typing_extensions___Literal["result", b"result"]
    ) -> None: ...

type___OaasUnregisterServiceResponse = OaasUnregisterServiceResponse
