= Germanium Build System

The Germanium Build System (GBS from now on) is centered around building any
software on any technology stack, using docker as a driving force to provision
reproducible build containers, jenkins to automate flows end-to-end and build
inter dependencies.

In order to achieve that, GBS requires the definition of script files that are
inside the `_gbs` folder, defining what steps should be required in order
to build the application.

Each step is defined in the same way as lifecycles that are part of maven. In
case they are missing, then a default version will run depending on the
technology stack.

The steps are defined in two stages. The first one, is the build, that will run
in the build container, the second one is the run container. The run container
should only contain the packages that are needed to run the application.

Each stage is a folder in the `_gbs` folder, so there will be a `_gbs/build/`
and a `_gbs/run/` folder.

If the files are empty they are not considered.

The steps will be ran in the `/src/` folder. The original scripts that are
packaged in the top image can be found in `/_gbs/build/...` or `/_gbs/run/...`.

Steps defined:

== Build Container

1. install-software [as root]
Will install the software required to test the software. Since this can be
quite big it will be cached in the upper layers. This is the only file will run
as root.

2. prepare-build1 [as germanium]
Will try to download core dependencies that are needed for the build. This is a
caching stage. Each caching stage will allow installing some dependincies in
order.

3. prepare-build2 [as germanium]
Will do setups just before the build. This is another caching layer for
downloading external dependencies (for example in the world of
germanium-drivers, the fetching of the binary drivers).

4. prepare-build3 [as germanium]
The last caching stage, things that change the most often.

5. run-build [as germanium]
Will do the actual build run. This should yield the final artifacts that are
the actual output. Only here the environment arguments are visible.

== Final Container

1. install-software [as root]

2. prepare-run [as germanium]

3. run [as germanium]

Will run the application. Should probably be rewritten to match the
requirements.

Only here the parameters for the run are available.
